### ISSUE TITLE
✓ All prerequisites met! but still failing

### ISSUE THREAD

**Issue by FurkanGozukara** [erew123/deepspeedpatcher#3]
First of all thank you so much for this tool

I believe I have everything but still failing any help appreciated @erew123 
```

[2024-12-12 01:22:17] DeepSpeed Windows Patcher Started
[2024-12-12 01:22:17] 
Checking prerequisites...
[2024-12-12 01:22:17] 
Checking Visual Studio installation:
[2024-12-12 01:22:17] ✓ Found VS2019 BuildTools at: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
[2024-12-12 01:22:17] 
Checking CUDA installation:
[2024-12-12 01:22:17] ✓ Found CUDA installation at: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
[2024-12-12 01:22:17] ✓ Found nvcc compiler
[2024-12-12 01:22:17] 
Checking Python packages:
[2024-12-12 01:22:17] ✓ torch 2.5.0+cu124 is installed
[2024-12-12 01:22:17]   ✓ CUDA is available for PyTorch
[2024-12-12 01:22:17]   ✓ CUDA Version: 12.4
[2024-12-12 01:22:17] ✓ ninja is installed
[2024-12-12 01:22:17] ✓ psutil is installed
[2024-12-12 01:22:17] 
✓ All prerequisites met!
[2024-12-12 01:22:26] 
Build Environment:
[2024-12-12 01:22:26] Python Version: 3.10.11
[2024-12-12 01:22:26] PyTorch Version: 2.5.0+cu124
[2024-12-12 01:22:26] Selected CUDA Version: 12.4
[2024-12-12 01:22:26] Building DeepSpeed Version: 0.15.3

[2024-12-12 01:22:27] Cleaning existing build directory...
[2024-12-12 01:22:27] Downloading DeepSpeed 0.15.3...
[2024-12-12 01:22:27] Download URL: https://github.com/microsoft/DeepSpeed/archive/v0.15.3.zip
[2024-12-12 01:22:37] Extracting files...

        
[2024-12-12 01:22:38] Using Visual Studio 64-bit tools from: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
[2024-12-12 01:22:38] Starting build with 64-bit tools...
[2024-12-12 01:22:38] **********************************************************************
[2024-12-12 01:22:38] ** Visual Studio 2019 Developer Command Prompt v16.11.42
[2024-12-12 01:22:38] ** Copyright (c) 2021 Microsoft Corporation
[2024-12-12 01:22:38] **********************************************************************
[2024-12-12 01:22:38] [vcvarsall.bat] Environment initialized for: 'x64'
[2024-12-12 01:22:38] ============ Environment Variables ============
[2024-12-12 01:22:38] CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
[2024-12-12 01:22:38] CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
[2024-12-12 01:22:38] PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;C:\Python310\Scripts;C:\Python310;C:\Python312\Scripts\;C:\Python312\;C:\Program Files\ImageMagick-7.1.1-Q16;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp;C:\cudnn_8.9;C:\Program Files\NVIDIA\CUDNN\v9.4\bin;C:\Python311\Scripts;C:\Python311;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet;C:\Program Files (x86)\Incredibuild;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files\NVIDIA Corporation\Nsight Compute 2024.1.0;C:\ffmpeg_latest;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\runpodctl_exe;C:\Users\Furkan\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
[2024-12-12 01:22:38] INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt
[2024-12-12 01:22:38] Platform: x64
[2024-12-12 01:22:38] ============================================
[2024-12-12 01:22:40] test.c
[2024-12-12 01:22:40] LINK : fatal error LNK1181: cannot open input file 'aio.lib'
[2024-12-12 01:22:48] test.c
[2024-12-12 01:22:48] LINK : fatal error LNK1181: cannot open input file 'cufile.lib'
[2024-12-12 01:22:48] DS_BUILD_OPS=1
[2024-12-12 01:22:48] [93m [WARNING] [0m Skip pre-compile of incompatible gds; One can disable gds with DS_BUILD_GDS=0
[2024-12-12 01:22:48] Install Ops={'async_io': False, 'fused_adam': 1, 'cpu_adam': 1, 'cpu_adagrad': 1, 'cpu_lion': 1, 'evoformer_attn': False, 'fp_quantizer': False, 'fused_lamb': 1, 'fused_lion': 1, 'gds': False, 'transformer_inference': 1, 'inference_core_ops': 1, 'cutlass_ops': False, 'quantizer': 1, 'ragged_device_ops': False, 'ragged_ops': 1, 'random_ltd': 1, 'sparse_attn': False, 'spatial_inference': 1, 'transformer': 1, 'stochastic_transformer': 1}
[2024-12-12 01:22:48] Traceback (most recent call last):
[2024-12-12 01:22:48] File "C:\deepspeedpatcher\deepspeed\setup.py", line 209, in <module>
[2024-12-12 01:22:48] result = subprocess.check_output(git_hash_cmd)
[2024-12-12 01:22:48] File "C:\Python310\lib\subprocess.py", line 421, in check_output
[2024-12-12 01:22:48] return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
[2024-12-12 01:22:48] File "C:\Python310\lib\subprocess.py", line 503, in run
[2024-12-12 01:22:48] with Popen(*popenargs, **kwargs) as process:
[2024-12-12 01:22:48] File "C:\Python310\lib\subprocess.py", line 971, in __init__
[2024-12-12 01:22:48] self._execute_child(args, executable, preexec_fn, close_fds,
[2024-12-12 01:22:48] File "C:\Python310\lib\subprocess.py", line 1456, in _execute_child
[2024-12-12 01:22:48] hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
[2024-12-12 01:22:48] FileNotFoundError: [WinError 2] The system cannot find the file specified
[2024-12-12 01:22:49] Build process error: Build failed
[2024-12-12 01:22:49] Error during build: Build failed

```

**Comment by FurkanGozukara** [comment]
i doubt that this works

i fixed several errors but another error keep popping up



```
[2024-12-12 01:51:32] Python Version: 3.10.11
[2024-12-12 01:51:32] PyTorch Version: 2.5.0+cu124
[2024-12-12 01:51:32] Selected CUDA Version: 12.4
[2024-12-12 01:51:32] Building DeepSpeed Version: 0.15.3

[2024-12-12 01:51:33] Build directory already exists: C:\deepspeedpatcher\deepspeed
[2024-12-12 01:51:33] DeepSpeed 0.15.3 already downloaded and extracted.
[2024-12-12 01:51:33] Using Visual Studio 64-bit tools from: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
[2024-12-12 01:51:33] Starting build with 64-bit tools...
[2024-12-12 01:51:33] **********************************************************************
[2024-12-12 01:51:33] ** Visual Studio 2022 Developer Command Prompt v17.8.14
[2024-12-12 01:51:33] ** Copyright (c) 2022 Microsoft Corporation
[2024-12-12 01:51:33] **********************************************************************
[2024-12-12 01:51:33] [vcvarsall.bat] Environment initialized for: 'x64'
[2024-12-12 01:51:33] ============ Environment Variables ============
[2024-12-12 01:51:33] CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
[2024-12-12 01:51:33] CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
[2024-12-12 01:51:33] PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\;C:\Program Files\Git\cmd;C:\Python310\Scripts;C:\Python310;C:\Python312\Scripts\;C:\Python312\;C:\Program Files\ImageMagick-7.1.1-Q16;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp;C:\cudnn_8.9;C:\Program Files\NVIDIA\CUDNN\v9.4\bin;C:\Python311\Scripts;C:\Python311;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet;C:\Program Files (x86)\Incredibuild;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files\NVIDIA Corporation\Nsight Compute 2024.1.0;C:\ffmpeg_latest;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\runpodctl_exe;C:\Users\Furkan\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64\bin;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
[2024-12-12 01:51:33] INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
[2024-12-12 01:51:33] Platform: x64
[2024-12-12 01:51:33] ============================================
[2024-12-12 01:51:34] [2024-12-12 01:51:34,820] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-12 01:51:35] Traceback (most recent call last):
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\setup.py", line 40, in <module>
[2024-12-12 01:51:35] from op_builder import get_default_compute_capabilities, OpBuilder
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\op_builder\__init__.py", line 18, in <module>
[2024-12-12 01:51:35] import deepspeed.ops.op_builder  # noqa: F401 # type: ignore
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\__init__.py", line 25, in <module>
[2024-12-12 01:51:35] from . import ops
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\__init__.py", line 11, in <module>
[2024-12-12 01:51:35] from . import transformer
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\__init__.py", line 7, in <module>
[2024-12-12 01:51:35] from .inference.config import DeepSpeedInferenceConfig
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\__init__.py", line 7, in <module>
[2024-12-12 01:51:35] from ....model_implementations.transformers.ds_transformer import DeepSpeedTransformerInference
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\model_implementations\__init__.py", line 6, in <module>
[2024-12-12 01:51:35] from .transformers.ds_transformer import DeepSpeedTransformerInference
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\model_implementations\transformers\ds_transformer.py", line 18, in <module>
[2024-12-12 01:51:35] from deepspeed.ops.transformer.inference.triton.mlp import TritonMLP
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\triton\__init__.py", line 10, in <module>
[2024-12-12 01:51:35] from .ops import *
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\triton\ops.py", line 6, in <module>
[2024-12-12 01:51:35] import deepspeed.ops.transformer.inference.triton.matmul_ext as matmul_ext
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 461, in <module>
[2024-12-12 01:51:35] fp16_matmul = Fp16Matmul()
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 210, in __init__
[2024-12-12 01:51:35] __class__._read_autotune_table()
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 444, in _read_autotune_table
[2024-12-12 01:51:35] TritonMatmul._read_autotune_table(__class__.__name__ + "_2d_kernel", __class__._2d_kernel)
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 165, in _read_autotune_table
[2024-12-12 01:51:35] cache_manager = AutotuneCacheManager(cache_key)
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 87, in __init__
[2024-12-12 01:51:35] TritonCacheDir.warn_if_nfs(self.cache_dir)
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 44, in warn_if_nfs
[2024-12-12 01:51:35] if is_nfs_path(cache_dir) and not TritonCacheDir._warning_printed:
[2024-12-12 01:51:35] File "C:\deepspeedpatcher\deepspeed\deepspeed\ops\transformer\inference\triton\matmul_ext.py", line 27, in is_nfs_path
[2024-12-12 01:51:35] output = subprocess.check_output(['df', '-T', path], encoding='utf-8')
[2024-12-12 01:51:35] File "C:\Python310\lib\subprocess.py", line 421, in check_output
[2024-12-12 01:51:35] return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
[2024-12-12 01:51:35] File "C:\Python310\lib\subprocess.py", line 503, in run
[2024-12-12 01:51:35] with Popen(*popenargs, **kwargs) as process:
[2024-12-12 01:51:35] File "C:\Python310\lib\subprocess.py", line 971, in __init__
[2024-12-12 01:51:35] self._execute_child(args, executable, preexec_fn, close_fds,
[2024-12-12 01:51:35] File "C:\Python310\lib\subprocess.py", line 1456, in _execute_child
[2024-12-12 01:51:35] hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
[2024-12-12 01:51:35] FileNotFoundError: [WinError 2] The system cannot find the file specified
[2024-12-12 01:51:35] Build process error: Build failed
[2024-12-12 01:51:35] Error during build: Build failed
```

**Comment by erew123** [comment]
Hi @FurkanGozukara 

Sorry but I don't have time to test every variation, PyTorch version, CUDA version etc, which is part of the reason I don't provide any support for this https://github.com/erew123/deepspeedpatcher?tab=readme-ov-file#support 

I've tested with this today:

![image](https://github.com/user-attachments/assets/7236540c-930b-4c8d-ab13-fdde6317f2cb)

and it has built fine:

![image](https://github.com/user-attachments/assets/14dd4df9-223a-4c67-ba77-4a4e185a4dbd)

My belief would be that your issue is based around using PyTorch 2.5 and possibly CUDA 12.4, but more likely PyTorch 2.5.

I dont know if that is something that would be resolved by building a DeepSpeed v16.x wheel, but you can add those using this method https://github.com/erew123/deepspeedpatcher?tab=readme-ov-file#configuration-file-deepspeed_configjson

I would suggest sticking with the manual build process as it will be quicker and cleaner to debug/test. Make sure you are in an administrative command prompt before you start the `vcvars64.bat` which is **before** you build 

![image](https://github.com/user-attachments/assets/3e0f5990-a17d-45c3-8238-4c0be1ae3dbe)
